--99_춘대학_SELECT(FUNCTION)실습문제

--1.
SELECT STUDENT_NO 학번
      ,STUDENT_NAME 이름
      ,TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

--2
SELECT PROFESSOR_NAME
      ,PROFESSOR_SSN
FROM TB_PROFESSOR
--WHERE PROFESSOR_NAME NOT LIKE '___';
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3
SELECT PROFESSOR_NAME 교수이름
--      ,EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN,1,2),'RR'))
        ,EXTRACT(YEAR FROM SYSDATE) - (19||SUBSTR(PROFESSOR_SSN,1,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1';

--4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO
      ,STUDENT_NAME
FROM TB_STUDENT
--입학년도 - 출생년도 가 19보다 크면 (재수)
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) > 19;

--6.
SELECT TO_CHAR(TO_DATE('20201225'),'DAY')
FROM DUAL;

--7.
SELECT TO_DATE('99/10/11','YY/MM/DD') --2099
      ,TO_DATE('49/10/11','YY/MM/DD') --2049
      ,TO_DATE('99/10/11','RR/MM/DD') --1999
      ,TO_DATE('49/10/11','RR/MM/DD') --2049
FROM DUAL;

--8
SELECT STUDENT_NO
      ,STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10
SELECT DEPARTMENT_NO 학과번호
      ,COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO,1,4) 년도
      ,ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 년도;

--13
SELECT DEPARTMENT_NO 학과코드명
      ,COUNT(ABSENCE_YN) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 1;
--위와같이 표현하면 없는 학과코드는 표현이 안됨 

SELECT DEPARTMENT_NO 학과코드명
      ,COUNT(DECODE(ABSENCE_YN,'Y',1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14
SELECT STUDENT_NAME 동일이름
      ,COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

--15.
--ROLLUP : 총계를 계산해주는 함수
--GROUP BY ROLLUP(컬럼1,컬럼2,..) - 컬럼1과 컬럼2의 전체 총계를 내어준다
SELECT NVL(SUBSTR(TERM_NO,1,4),' ') 년도
      ,NVL(SUBSTR(TERM_NO,5,2),' ') 학기
      ,ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO ='A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY 1;











