--KH 연습문제
--1번
--ANSI
SELECT
    EMP_NAME
    ,EMP_NO
    ,DEPT_TITLE
    ,JOB_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
LEFT JOIN JOB USING (JOB_CODE)
WHERE 
    SUBSTR(EMP_NO,8,1)=2
    AND EMP_NAME LIKE '전%'
    AND SUBSTR(EMP_NO,1,1) =7;
--ORACLE
SELECT
    EMP_NAME
    ,EMP_NO
    ,DEPT_TITLE
    ,JOB_NAME
FROM EMPLOYEE E, DEPARTMENT D,JOB J
WHERE 
    DEPT_CODE=DEPT_ID(+)
    AND E.JOB_CODE=J.JOB_CODE(+)
    AND SUBSTR(EMP_NO,8,1)=2
    AND EMP_NAME LIKE '전%'
    AND SUBSTR(EMP_NO,1,1) =7;

--2
SELECT
    DEPT_CODE
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--ANSI
SELECT
    EMP_ID
    ,EMP_NAME
    ,EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6))) 나이
    ,DEPT_TITLE
    ,JOB_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
LEFT JOIN JOB USING (JOB_CODE)
WHERE 
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6)))
    = (SELECT
        MIN(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6))))
        FROM EMPLOYEE
        );

--ORACLE
SELECT
    EMP_ID
    ,EMP_NAME
    ,EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6))) 나이
    ,DEPT_TITLE
    ,JOB_NAME
FROM EMPLOYEE E,DEPARTMENT D,JOB J
WHERE
    DEPT_CODE=DEPT_ID
    AND E.JOB_CODE=J.JOB_CODE
    AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6)))
        = (SELECT
            MIN(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO,1,6))))
            FROM EMPLOYEE
           );

--3
--ANSI
SELECT
    EMP_ID
    ,EMP_NAME
    ,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';
--ORACLE
SELECT
    EMP_ID
    ,EMP_NAME
    ,JOB_NAME
FROM EMPLOYEE E,JOB J
WHERE
    E.JOB_CODE=J.JOB_CODE
    AND EMP_NAME LIKE '%형%';
    
--4
--ANSI
SELECT
    EMP_NAME
    ,JOB_NAME
    ,DEPT_CODE
    ,DEPT_TITLE
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
WHERE DEPT_CODE IN ('D5','D6');
--ORACLE
SELECT
    EMP_NAME
    ,JOB_NAME
    ,DEPT_CODE
    ,DEPT_TITLE
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.JOB_CODE=J.JOB_CODE
    AND DEPT_CODE=DEPT_ID
    AND DEPT_CODE IN ('D5','D6');
    
--5
--ANSI
SELECT
    EMP_NAME
    ,BONUS
    ,DEPT_TITLE
    ,LOCAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN LOCATION ON (LOCATION_ID=LOCAL_CODE)
WHERE BONUS IS NOT NULL;
--ORACLE
SELECT
    EMP_NAME
    ,BONUS
    ,DEPT_TITLE
    ,LOCAL_NAME
FROM EMPLOYEE E,DEPARTMENT D,LOCATION L
WHERE
    DEPT_CODE=DEPT_ID
    AND LOCATION_ID=LOCAL_CODE
    AND BONUS IS NOT NULL;

--6
--ANSI
SELECT
    EMP_NAME
    ,JOB_NAME
    ,DEPT_TITLE
    ,LOCAL_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN LOCATION ON (LOCATION_ID=LOCAL_CODE);
--ORACLE
SELECT
    EMP_NAME
    ,JOB_NAME
    ,DEPT_TITLE
    ,LOCAL_NAME
FROM EMPLOYEE E,JOB J,DEPARTMENT,LOCATION
WHERE
    DEPT_CODE = DEPT_ID
    AND E.JOB_CODE=J.JOB_CODE
    AND LOCATION_ID = LOCAL_CODE;
    
--7
--ANSI
SELECT
    EMP_NAME
    ,DEPT_TITLE
    ,LOCAL_NAME
    ,NATIONAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN LOCATION ON (LOCATION_ID=LOCAL_CODE)
JOIN NATIONAL USING (NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국','일본');
--ORACLE
SELECT
    EMP_NAME
    ,DEPT_TITLE
    ,LOCAL_NAME
    ,NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE
    DEPT_CODE=DEPT_ID
    AND LOCATION_ID=LOCAL_CODE
    AND L.NATIONAL_CODE=N.NATIONAL_CODE
    AND NATIONAL_NAME IN ('한국','일본');
--8
--ANSI
SELECT
    E1.EMP_NAME
    ,E1.DEPT_CODE
    ,E2.EMP_NAME
FROM EMPLOYEE E1 --기준
JOIN EMPLOYEE E2 ON (E1.DEPT_CODE = E2.DEPT_CODE)
WHERE E1.EMP_NAME <> E2.EMP_NAME
ORDER BY 1;--기준과 같은 부서 사람
--ORACLE
SELECT
    E1.EMP_NAME
    ,E1.DEPT_CODE
    ,E2.EMP_NAME
FROM EMPLOYEE E1 ,EMPLOYEE E2
WHERE 
    E1.DEPT_CODE = E2.DEPT_CODE
    AND E1.EMP_NAME <> E2.EMP_NAME
ORDER BY 1;

--9
--ANSI
SELECT
    EMP_NAME
    ,JOB_NAME
    ,SALARY
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE
    BONUS IS NULL
    AND JOB_CODE IN ('J4','J7');
--ORACLE
SELECT
    EMP_NAME
    ,JOB_NAME
    ,SALARY
FROM EMPLOYEE E,JOB J
WHERE
    E.JOB_CODE = J.JOB_CODE
    AND BONUS IS NULL
    AND E.JOB_CODE IN ('J4','J7');

--10
--ANSI
SELECT
    EMP_ID
    ,EMP_NAME
    ,DEPT_TITLE
    ,JOB_NAME
    ,HIRE_DATE
    ,(SALARY+SALARY*NVL(BONUS,0)) "최종 연봉"
    ,'순위?'
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
JOIN JOB USING (JOB_CODE)
ORDER BY SALARY+SALARY*NVL(BONUS,0) DESC
FETCH FIRST 5 ROWS ONLY;

--ORACLE
SELECT
    EMP_ID
    ,EMP_NAME
    ,DEPT_TITLE
    ,JOB_NAME
    ,HIRE_DATE
    ,(SALARY+SALARY*NVL(BONUS,0)) "최종 연봉"
    ,'순위?'
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE  
    DEPT_CODE = DEPT_ID
    AND E.JOB_CODE = J.JOB_CODE
    ORDER BY SALARY+SALARY*NVL(BONUS,0) DESC
FETCH FIRST 5 ROWS ONLY;

    