--춘대학 고급 문제 풀이
--1
SELECT
    STUDENT_NAME
    ,STUDENT_ADDRESS
FROM TB_STUDENT
ORDER BY 1 ASC;

--2
SELECT
    STUDENT_NAME
    ,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

--3
SELECT
    STUDENT_NAME "학생이름"
    ,SUBSTR(STUDENT_NO,2) "학번"
    ,STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE
    SUBSTR(STUDENT_ADDRESS,1,2) IN ('경기','강원')
    AND SUBSTR(STUDENT_NO,2,1) = '9'
ORDER BY 1;

--4 ANSI
SELECT
    PROFESSOR_NAME
    ,PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY SUBSTR(PROFESSOR_SSN,1,6);

--4 ORACLE
SELECT
    PROFESSOR_NAME
    ,PROFESSOR_SSN
FROM TB_PROFESSOR P, TB_DEPARTMENT D
WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND DEPARTMENT_NAME = '법학과'
ORDER BY SUBSTR(PROFESSOR_SSN,1,6);
 
 --5 ANSI
 SELECT
    STUDENT_NO
    ,TO_CHAR(POINT,'0.00')
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE
    TERM_NO = '200402'
    AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;
 
--5 ORACLE
SELECT
    S.STUDENT_NO
    ,TO_CHAR(POINT,'0.00')
FROM TB_STUDENT S, TB_GRADE G
WHERE
    S.STUDENT_NO = G.STUDENT_NO
    AND TERM_NO = '200402'
    AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--6 ANSI
SELECT
    STUDENT_NO
    ,STUDENT_NAME
    ,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--6 ANSI
SELECT
    STUDENT_NO
    ,STUDENT_NAME
    ,DEPARTMENT_NAME
FROM TB_STUDENT S, TB_DEPARTMENT T
WHERE S.DEPARTMENT_NO = T.DEPARTMENT_NO
ORDER BY STUDENT_NAME;

--7 ANSI
SELECT
    CLASS_NAME
    ,DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 1;

--7 ORACLE
SELECT
    CLASS_NAME
    ,DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY 1;

--8 ANSI
SELECT
    CLASS_NAME
    ,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

--8 ORACLE
SELECT
    CLASS_NAME
    ,PROFESSOR_NAME
FROM TB_CLASS C,TB_CLASS_PROFESSOR CP, TB_PROFESSOR P
WHERE 
    C.CLASS_NO = CP.CLASS_NO
    AND CP.PROFESSOR_NO = P.PROFESSOR_NO;

--9 ANSI
SELECT
    CLASS_NAME
    ,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
WHERE
    CATEGORY = '인문사회';
    
--9 ORACLE
SELECT
    CLASS_NAME
    ,PROFESSOR_NAME
FROM TB_CLASS C,TB_DEPARTMENT D,TB_CLASS_PROFESSOR CP, TB_PROFESSOR P
WHERE 
    C.CLASS_NO = CP.CLASS_NO
    AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND CP.PROFESSOR_NO = P.PROFESSOR_NO
    AND CATEGORY = '인문사회';
    
--10 ANSI
SELECT
    STUDENT_NO "학번"
    ,STUDENT_NAME "학생 이름"
    ,ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE
    DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO,STUDENT_NAME;

--10 ORACLE
SELECT
    S.STUDENT_NO "학번"
    ,S.STUDENT_NAME "학생 이름"
    ,ROUND(AVG(G.POINT),1) "전체 평점"
FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
WHERE
    S.STUDENT_NO = G.STUDENT_NO
    AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO,S.STUDENT_NAME;

--11 ANSI
SELECT
    DEPARTMENT_NAME 학과이름
    ,STUDENT_NAME 학생이름
    ,PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--11 ORACLE
SELECT
    DEPARTMENT_NAME 학과이름
    ,STUDENT_NAME 학생이름
    ,PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE
    S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
    AND STUDENT_NO = 'A313047';
    
--12 ANSI
SELECT
    STUDENT_NAME
    ,TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE 
    SUBSTR(TERM_NO,1,4) = '2007'
    AND CLASS_NAME = '인간관계론';

--12 ORACLE
SELECT
    STUDENT_NAME
    ,TERM_NO
FROM TB_STUDENT S, TB_GRADE G, TB_CLASS C
WHERE 
    S.STUDENT_NO = G.STUDENT_NO
    AND G.CLASS_NO = C.CLASS_NO
    AND SUBSTR(TERM_NO,1,4) = '2007'
    AND CLASS_NAME = '인간관계론';
    
--13 ANSI
SELECT
    CLASS_NAME
    ,DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
LEFT JOIN TB_PROFESSOR USING (PROFESSOR_NO)
WHERE
    CATEGORY = '예체능'
    AND PROFESSOR_NAME IS NULL;

--13 ORACLE
SELECT
    CLASS_NAME
    ,DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D, TB_CLASS_PROFESSOR CP, TB_PROFESSOR P
WHERE
    C.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND C.CLASS_NO = CP.CLASS_NO(+)
    AND CP.PROFESSOR_NO = P.PROFESSOR_NO(+)
    AND CATEGORY = '예체능'
    AND PROFESSOR_NAME IS NULL;
    
--14 ANSI
SELECT
    STUDENT_NAME "학생이름"
    ,NVL(PROFESSOR_NAME,'지도교수 미지정') "지도교수"
FROM TB_STUDENT S
--LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO AND DEPARTMENT_NAME = '서반어학과')
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

--14 ORACLE
SELECT
    S.STUDENT_NAME "학생이름"
    ,NVL(P.PROFESSOR_NAME,'지도교수 미지정') "지도교수"
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE 
    S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
    AND DEPARTMENT_NAME = '서반아어학과';
    
--15 ANSI
SELECT
    STUDENT_NO
    ,STUDENT_NAME
    ,DEPARTMENT_NAME
    ,ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY
    STUDENT_NO
    ,STUDENT_NAME
    ,DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;

--15 ORACLE
SELECT
    S.STUDENT_NO
    ,S.STUDENT_NAME
    ,D.DEPARTMENT_NAME
    ,ROUND(AVG(POINT),1)
FROM TB_STUDENT S,TB_DEPARTMENT D, TB_GRADE G
WHERE 
    S.DEPARTMENT_NO = D.DEPARTMENT_NO
    AND S.STUDENT_NO = G.STUDENT_NO
    AND ABSENCE_YN = 'N'
GROUP BY
    S.STUDENT_NO
    ,S.STUDENT_NAME
    ,D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;

--16 ANSI
SELECT
    C.CLASS_NO
    ,CLASS_NAME
    ,ROUND(AVG(POINT),2)
FROM TB_CLASS C
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
GROUP BY
    C.CLASS_NO
    ,CLASS_NAME
ORDER BY 1;

--16 ORACLE
SELECT
    C.CLASS_NO
    ,CLASS_NAME
    ,ROUND(AVG(POINT),2)
FROM TB_CLASS C , TB_STUDENT S, TB_GRADE G

WHERE 
    C.DEPARTMENT_NO = S.DEPARTMENT_NO
    AND S.STUDENT_NO = G.STUDENT_NO
GROUP BY
    C.CLASS_NO
    ,CLASS_NAME
ORDER BY 1;

