WITH SUB AS(
SELECT
    CLASS_NO 과목번호
    ,CLASS_NAME 과목이름
    ,COUNT(*) "누적수강생수(명)"
    ,RANK() OVER (ORDER BY COUNT(*)DESC) 순위
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) BETWEEN 2005 AND 2009
GROUP BY CLASS_NO,CLASS_NAME
)
SELECT
    과목번호
    ,과목이름
    ,"누적수강생수(명)"
FROM SUB
WHERE 순위<=3;