--JDBC용 스크립트
--JDBC 테스트용 테이블 생성
CREATE TABLE TEST(
    TNO NUMBER,
    TNAME VARCHAR2(20),
    TDATE DATE
);

SELECT * FROM TEST;

//자료 재설정
DELETE
FROM TEST;

INSERT ALL 
    INTO TEST VALUES(1,'김일번','01/01/01')
    INTO TEST VALUES(2,'박이번','01/01/02')
    INTO TEST VALUES(3,'최삼번','01/01/03')
SELECT * FROM DUAL;

COMMIT;

--멤버 테이블 생성
CREATE TABLE MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) UNIQUE NOT NULL,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(3) CHECK(GENDER IN('남','여')) NOT NULL,
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    ENROLLDATE DATE DEFAULT SYSDATE
);

--시퀀스 생성
CREATE SEQUENCE SEQ_MNO NOCACHE;

INSERT INTO MEMBER VALUES(SEQ_MNO.NEXTVAL,'user01','pass01','김유저','남',20,
                            'user@gmail.com','01068994376','수풍로 38',SYSDATE);
COMMIT;

DELETE FROM MEMBER;
SELECT * FROM MEMBER;


-----------

CREATE TABLE BOOK(
    BOOK_NO NUMBER PRIMARY KEY
    ,BOOK_TITLE VARCHAR2(100) NOT NULL
    ,AUTHOR VARCHAR2(50) NOT NULL
    ,CATEGORY VARCHAR2(30) NOT NULL
    ,PRICE NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_BNO NOCACHE;